export const GET_INSTITUTIONS_TYPE = "GET_INSTITUTIONS_TYPE";
export const GET_INSTITUTIONS = "GET_INSTITUTIONS";
export const GET_STATES = "GET_STATES";
export const GET_CITIES = "GET_CITIES";
export const GET_ROLES = "GET_ROLES";
export const GET_EVENTS = "GET_EVENTS";

export const LOGIN = "LOGIN";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const LOGOUT = "LOGOUT";
export const POST_ADD_USER = "POST_ADD_USER";
export const CLOSE_SNACKBAR_REGISTER = "CLOSE_SNACKBAR_REGISTER";
export const POST_ADD_INSTITUTION = "POST_ADD_INSTITUTION";



export const GET_INSTITUTION_USER = "GET_INSTITUTION_USER";

