export const GET_INSTITUTIONS_TYPE = "GET_INSTITUTIONS_TYPE";
export const GET_INSTITUTIONS = "GET_INSTITUTIONS";
export const GET_STATES = "GET_STATES";
export const GET_CITIES = "GET_CITIES";
export const GET_ROLES = "GET_ROLES";
export const GET_EVENTS = "GET_EVENTS";

export const LOGIN = "LOGIN";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const LOGOUT = "LOGOUT";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_INSTITUTION = "LOGOUT_INSTITUTION";
export const POST_ADD_USER = "POST_ADD_USER";
export const PUT_USER = "PUT_USER";
export const CLOSE_SNACKBAR_REGISTER = "CLOSE_SNACKBAR_REGISTER";
export const POST_ADD_INSTITUTION = "POST_ADD_INSTITUTION";

export const POST_ADD_EVENT = "POST_ADD_EVENT";
export const CLOSE_SNACKBAR_EVENT = "CLOSE_SNACKBAR_EVENT";

export const GET_USER_INSTITUTION = "GET_USER_INSTITUTION";
export const POST_USER_INSTITUTION = "POST_USER_INSTITUTION";
export const REMOVE_USER_INSTITUTION = "REMOVE_USER_INSTITUTION";
export const CLOSE_SNACKBAR_USER_INSTITUTION = "CLOSE_SNACKBAR_USER_INSTITUTION";

export const GET_INSTITUTION_USERS = "GET_INSTITUTION_USERS";
export const APPROVE_INSTITUTION_USER = "APPROVE_INSTITUTION_USER";
export const REMOVE_INSTITUTION_USER = "REMOVE_INSTITUTION_USER";
export const CLOSE_SNACKBAR_INSTITUTION_USER = "CLOSE_SNACKBAR_INSTITUTION_USER";

export const GET_DONATION_USER = "GET_DONATION_USER";
export const ADD_DONATION_USER = "ADD_DONATION_USER"
export const REMOVE_DONATION_USER = "REMOVE_DONATION_USER"
export const CLOSE_SNACKBAR_DONATION_USER = "CLOSE_SNACKBAR_DONATION_USER"

export const GET_DONATION_INSTITUTION = "GET_DONATION_INSTITUTION";
export const ADD_DONATION_INSTITUTION = "ADD_DONATION_INSTITUTION"
export const REMOVE_DONATION_INSTITUTION = "REMOVE_DONATION_INSTITUTION"
export const CLOSE_SNACKBAR_DONATION_INSTITUTION = "CLOSE_SNACKBAR_DONATION_INSTITUTION"
